exports.trans = {
	"Leak  test":	"测漏",
	"Flush rinse":	"冲洗",
	"Wash":			"清洗剂清洗",
	"Post rinse":	"漂洗",
	"Final rinse":	"末洗",
	"Disinfection":	"消毒",
	"Vent":			"吹干",
	"Detergent contact time":	"清洁剂接触时间",
	"Rinse contact time":	"清洗接触时间",
	"Disinfectant contact time":	"消毒接触时间",
	"Basin temperature":	"槽内温度",
	"Alcohol delivered":	"酒精吹干",
	"No pressure water channel":	"水腔道无压力",
	"No pressure jet channel":	"水气腔道无压力",
	"No pressure air channel":	"空气腔道无压力",
	"No pressure extra channel":	"extra腔道无压力",
	"No pressure biopsy channel":	"活检腔道无压力",
	"No pressure suction channel":	"吸引腔道无压力",
	"No pressure elevator channel":	"附送水腔道无压力",
	"Biopsy channel disconnected":	"活检腔道未连接",
	"Water channel disconnected":	"水腔道未连接",
	"Air channel disconnected":		"空气腔道未连接",
	"SCU F-075/S095 (Minimum spray arm speed)":	"SCU F-075/S095 (最小喷射臂速度)",
	"Spray arm speed below minimum":	"喷射臂速度低于最小",
	"Block not pressurized or not connected":	"堵塞无增压或无连接",
	"Minor endoscope leak, cycle continuing safely":	"内镜轻微漏气,循环继续平稳进行",
	"Water inlet flow too low":	"入口水流过低",
	"Start not allowed: Detergent level low": "不允许开始:清洁剂水平低",
	"Start not allowed: Alcohol level low": "不允许开始:酒精水平低",
	"No alcohol flow":	"无酒精流",
	"No flow air channel": "空气通道无流",
	"Manual control active":	"手动控制激活",
	"Stopped by operator": "被操作者停止",
	"Elevator channel disconnected": "附送水腔道未连接",
	"Hookup": "模块",
	"Connection check": "连接性检测",
	"Drain both basins": "双槽排水",
	"Fill Part A/B dosing reservoirs": "A/B液注入定量器",
	"Chemical": "A/B液制备",
	"Dosing [Soap]": "A/B液配比混匀",
	"Fill and check channels [all]": "注入并检测腔道（全部）",
	"Fill basin": "清洗槽注入",
	"Wait to add chemical to water": "等待化学制剂入水",
	"Wait to disconnect water supply": "等待断开供水",
	"Circulating fluid through channels": "通过腔道液体混匀",
	"Disinfect the water lines and water filter": "消毒供水管路和水过滤器",
	"Disinfect the basins": "消毒清洗槽",
	"Wait to connect water supply": "等待连接供水",
	"Rinse the water lines": "漂洗供水管路",
	"Flushing endoscope channels": "冲洗腔道",
	"Rinse the basins": "漂洗清洗槽"
};
